блок фильтров сделан адаптивным
ISRPO2019/ISRPO2019.github.io pull request #107
Opened 2019-12-16 11:38 UTC by danil939

Зафиксировать #79

2019-12-16 11:40 UTC, FluffyF1sh submitted a review, later dismissed

2019-12-16 14:00 UTC, TeplCold requested changes
Где адаптация!? См.макет.
![image](https://user-images.githubusercontent.com/38286808/70912652-d8bb6b80-202d-11ea-9cc8-2864b28974ed.png)

2019-12-16 14:00 UTC, FluffyF1sh requested changes
!!!

2019-12-16 18:54 UTC, Vladislav-Lyuminarskiy commented
Ссылка на задачу в описании сделана некорректно.

2019-12-18 13:16 UTC, MamaikAn commented
Исправить css. В коде стоят размеры в px, ужать не получится.

2019-12-18 13:28 UTC, TeplCold requested changes
Картинки замени еще.
[filtr_sort.zip](https://github.com/ISRPO2019/ISRPO2019.github.io/files/3978529/filtr_sort.zip)

2019-12-18 13:38 UTC, FluffyF1sh requested changes
.

2019-12-21 22:41 UTC, TeplCold requested changes
Разреши конфликт.

2019-12-28 12:52 UTC, TeplCold requested changes
Я же попросил картинки заменить еще.
Адаптации нет!!! СМ.МАКЕТ.
![image](https://user-images.githubusercontent.com/38286808/71544133-aa764e00-2994-11ea-839d-14e72391ab7b.png)

2019-12-29 17:23 UTC, FluffyF1sh requested changes
!!

2020-03-11 06:03 UTC, closed without merging