Добавил адаптивность к footer
ISRPO2019/ISRPO2019.github.io pull request #108
Opened 2019-12-16 16:04 UTC by Reptil0id

2019-12-16 18:53 UTC, Vladislav-Lyuminarskiy commented
Почему в описании нет ссылки на соответствующую задачу?

2019-12-16 19:58 UTC, TeplCold requested changes
Не смог проверить. Обнови свой репозиторий, пожалуйста!
![image](https://user-images.githubusercontent.com/38286808/70938596-ed185c00-205f-11ea-830c-acba9439e733.png)

2019-12-16 20:00 UTC, FluffyF1sh requested changes
!!

2019-12-17 18:08 UTC, TeplCold requested changes
Доработай. См.макет.
![image](https://user-images.githubusercontent.com/38286808/71022332-aab35580-2119-11ea-8c12-48f695273876.png)
![image](https://user-images.githubusercontent.com/38286808/71022343-b1da6380-2119-11ea-97d2-ff56f59bd427.png)

2019-12-19 11:26 UTC, TeplCold commented
Pull requests #122

2020-03-11 06:03 UTC, closed without merging