Добавлена адаптивность
ISRPO2019/ISRPO2019.github.io pull request #111
Opened 2019-12-18 12:52 UTC by ZakharPustovgarov

Fixes #78

2019-12-18 13:22 UTC, TeplCold requested changes
Исправить параграф, по макету 24px должен быть font-size на 1920*1080.
![image](https://user-images.githubusercontent.com/38286808/71089656-c458a980-21ba-11ea-9043-8105ae9848a1.png)
Размер картинки по макету 115x115.
![image](https://user-images.githubusercontent.com/38286808/71089694-d5a1b600-21ba-11ea-92dd-fe3a8732ccad.png)
Заголовок тоже исправить. По макету 48px шрифт. И лучше было использовать <h[1-6]> вместо <р>
![image](https://user-images.githubusercontent.com/38286808/71089837-14377080-21bb-11ea-8b0d-591869945f11.png)

2019-12-18 13:25 UTC, FluffyF1sh requested changes
!

2019-12-18 14:00 UTC, FluffyF1sh requested changes
Размер картинки в мобильной версии ломается полностью
![image](https://user-images.githubusercontent.com/37347360/71092230-4bf4e700-21c0-11ea-801b-dc0e3f2a56d3.png)

upd1: с полной версией всё в порядке, проблема была на моей стороне

2019-12-19 08:09 UTC, FluffyF1sh approved these changes
Принято.

2019-12-19 09:42 UTC, TeplCold approved these changes

2019-12-19 09:42 UTC, merged