Шапка сайта теперь адаптивна
ISRPO2019/ISRPO2019.github.io pull request #116
Opened 2019-12-18 15:02 UTC by WartVader

Ура...
Fixes #85

2019-12-18 18:32 UTC, TeplCold requested changes
Исправь.
![image](https://user-images.githubusercontent.com/38286808/71113159-75286e00-21e6-11ea-8a1f-8794e8ec8ca8.png)
![image](https://user-images.githubusercontent.com/38286808/71113837-e3b9fb80-21e7-11ea-9615-ff06585887ab.png)

2019-12-19 08:08 UTC, FluffyF1sh approved these changes
Принято.

2019-12-19 10:13 UTC, FluffyF1sh requested changes
Отклонено.

2019-12-19 10:38 UTC, TeplCold requested changes
Исправь, сделай отступы как на макете.
![image](https://user-images.githubusercontent.com/38286808/71166715-be230580-226c-11ea-89bc-5b2d85d079a8.png)
![image](https://user-images.githubusercontent.com/38286808/71166963-31c51280-226d-11ea-9b45-0feef18870b5.png)

2019-12-19 18:52 UTC, WartVader commented
Короче сейчас или никогда. в общем ошибку я почти исправил. Теперь только на 240 px ломается, ы.

2019-12-19 20:15 UTC, WartVader commented
Если вы не пимите, то я, то я.... Я за себя не ручаюсь, я могу принять крайние меры, я буду плакать так сильно, что весь город затонет ;-;

2019-12-20 16:34 UTC, WartVader commented
Кхе-кхе принимать будете?

2019-12-21 18:32 UTC, TeplCold approved these changes

2019-12-28 09:52 UTC, FluffyF1sh approved these changes

2019-12-28 10:10 UTC, merged