upd header
ISRPO2019/ISRPO2019.github.io pull request #171
Opened 2020-04-30 15:39 UTC by WartVader

#167

2020-04-30 15:42 UTC, FluffyF1sh approved these changes

2020-04-30 17:37 UTC, MamaikAn requested changes
Требуется изменить index.html на /index.html. Изменить в обоих файлах product.html и index.html

2020-04-30 17:39 UTC, FluffyF1sh requested changes
Действительно,  это я пропустил

2020-05-01 10:07 UTC, MamaikAn commented
И укажи к какому issue относится пул

2020-05-01 11:12 UTC, WartVader commented
Я же указал issue

2020-05-01 11:12 UTC, FluffyF1sh approved these changes

2020-05-01 11:19 UTC, WartVader commented
Давайте это использовать как переписку?

2020-05-01 11:19 UTC, WartVader commented
Как ваш день проходит?

2020-05-01 11:29 UTC, MamaikAn commented
Исправь название пула, пусть будет на русском

2020-05-01 11:43 UTC, WartVader commented
Сделал

2020-05-01 11:54 UTC, MamaikAn approved these changes

2020-05-01 11:54 UTC, MamaikAn commented
@TeplCold ждем твоего одобрения

2020-05-01 11:59 UTC, TeplCold approved these changes

2020-05-01 12:00 UTC, merged