#163
ISRPO2019/ISRPO2019.github.io pull request #172
Opened 2020-05-01 09:51 UTC by Reptil0id

2020-05-01 09:56 UTC, Reptil0id commented
Счетчик для корзины

2020-05-01 11:19 UTC, MamaikAn commented
Измени название пула на более конкретное и сделай пул Ready for review

2020-05-01 11:46 UTC, MamaikAn requested changes
1. Добавить на страницу index.html аналогичное действие по нажатию на кнопку покупки (находится рядом с каждым товаром)
2. На странице product.html по нажатию на "добавить в корзину", счетчик корзины должен увеличиваться соответственно числу, записанному в поле рядом с кнопкой. То есть если добавляем 7 штук часов, то корзина увеличивается на 7 штук. Также нужно сделать, что это поле изначально, при открытии страницы уже было заполнено значением 1.
3. Счетчик сейчас увеличивается при нажатии на "Добавить в корзину" только со второго раза. Исправить.

2020-05-01 11:48 UTC, FluffyF1sh requested changes
Причины выше

2020-05-01 20:15 UTC, MamaikAn requested changes
Уже неплохо, но нужно внести еще несколько исправлений.
Все указано в комментариях, но главное:
1. В мобильной версии корзина также должна отражать текущее значение счетчика.
2. При переходе между страницами результат должен сохраняться. Для этого и сделан localStorage.

2020-05-01 20:15 UTC, MamaikAn commented on assets/symbol-defs.svg
> +<svg aria-hidden="true" style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" onclick="addNum"
Убрать все, что касается функционала из файла, переместить в html.

2020-05-01 20:15 UTC, MamaikAn commented on index.html
> +		  <span id="add_num">0</span>
Согласно дизайну, есть разница когда в корзине 0 товаров и когда товаров >0. На скриншоте первое состояние, когда товаров = 0. Второе когда >0.
![image](https://user-images.githubusercontent.com/38722519/80838025-b141f580-8c00-11ea-84d5-9bc91e0aea9e.png)

2020-05-01 20:15 UTC, MamaikAn commented on product.html
> +		  <span id="add_num">0</span>
Аналогично
![image](https://user-images.githubusercontent.com/38722519/80838073-d46ca500-8c00-11ea-8947-845ce55cfed9.png)

2020-05-01 20:15 UTC, MamaikAn commented on product.html
> +              <button  type="button" value="+1" onclick="addNum()">Добавить в<br> корзину</button>
В данный момент, если в input поле не введено никаких значений, то при нажатии на кнопку добавить в корзину результат получается NaN. Если в поле число отсутствует, добавление производить не надо

2020-05-01 20:15 UTC, MamaikAn commented on scripts/localStorage.js
> +	if(document.getElementById('amount') != null) {count = parseInt(document.getElementById('amount').value);}
Переменную нужно хранить в localStorage

2020-05-01 20:18 UTC, FluffyF1sh requested changes
Не знаю, я просто делаю свою работу

2020-05-02 09:38 UTC, MamaikAn requested changes
1. На главной странице перестало работать добавление в корзину;
2. На главной странице не отображается количество товаров на разрешениях <992. На странице товара отображается.

Перед попыткой пула советую сначала сделать тесты, чтобы убедиться в работоспособности функционала.

2020-05-02 12:35 UTC, MamaikAn commented on scripts/localStorage.js
> +   	//if(buyCount != 0) {document.getElementsByClassName('add_num')[1].style.display = "flex";}
Убрать комментарии

2020-05-02 12:35 UTC, MamaikAn requested changes
При добавлении в корзину со страницы каталога, прибавляется сразу два товара. 
На странице товара при попытке добавить товар прибавляется число из поля *2.
Убрать лишние комментарии

2020-05-02 12:38 UTC, FluffyF1sh requested changes
Действительно, после клика счётчик идёт на +2, на отдельном товаре кол-во*2

2020-05-02 14:56 UTC, MamaikAn requested changes
Сейчас: ![image](https://user-images.githubusercontent.com/38722519/80867711-4941ec80-8c9e-11ea-98c0-4430ead9f7ac.png)
Должно быть: ![image](https://user-images.githubusercontent.com/38722519/80867702-3f1fee00-8c9e-11ea-82e9-57e006ca17af.png)

2020-05-02 16:10 UTC, TeplCold submitted a review, later dismissed

2020-05-02 19:57 UTC, MamaikAn commented
Пересоздать новый, в связи с переименованием своего репозитория.

2020-05-02 23:16 UTC, MamaikAn requested changes
Вот как выглядит 320px:
![image](https://user-images.githubusercontent.com/38722519/80894479-f559f680-8ce3-11ea-9ea1-7b2a3e5b9558.png)

А вот как выглядит 800px:
![image](https://user-images.githubusercontent.com/38722519/80894491-0acf2080-8ce4-11ea-97bc-6da54fcd29bf.png)

Надо чтобы везде соотношение картинки и текста с кружочком было одинаковое.

2020-05-02 23:16 UTC, MamaikAn commented on style/style.css
>  @media screen and (min-width: 834px) and (max-width: 991px){
Такого разрешения не существует. Есть от 768 до 991 - это планшет.

2020-05-02 23:16 UTC, MamaikAn commented on style/style.css
>  }
Теперь все, что ниже планшета идет под одну дудку. Посмотри как выглядит на телефоне 320 px, должно быть одинаково на всех разрешениях.

2020-05-03 11:26 UTC, MamaikAn requested changes
Обновить в соответствии с последними изменениями.
Убрать повторения стилей. Оставить одно
![image](https://user-images.githubusercontent.com/38722519/80913047-04738f80-8d4a-11ea-905d-60e283c63b2d.png)

2020-05-03 12:04 UTC, MamaikAn commented on style/style.css
> +}
Уже писал, что нет такого разрешения. Исправь min-width на 768.

2020-05-03 12:05 UTC, MamaikAn requested changes
Я верю

2020-05-03 12:13 UTC, MamaikAn approved these changes

2020-05-03 12:16 UTC, FluffyF1sh approved these changes

2020-05-03 12:17 UTC, TeplCold approved these changes

2020-05-03 12:17 UTC, merged