Ограничил количество выводимых товаров и добавил отмену сортировки
ISRPO2019/ISRPO2019.github.io pull request #178
Opened 2020-05-01 20:56 UTC by Mynalait

Fixes #164

2020-05-01 21:03 UTC, MamaikAn requested changes
При повторном нажатии на уже выбранный радио, не должен происходить пере-рендер.
Изменить название пулла по формату: (что сделано?), а не (что сделал?)

2020-05-01 21:04 UTC, FluffyF1sh requested changes
Я устал, босс

2020-05-01 21:08 UTC, MamaikAn commented
> Я устал, босс

терпи, пес-босс

2020-05-01 21:09 UTC, FluffyF1sh commented
> > Я устал, босс
> 
> терпи, пес-босс

Ок... наливай...

2020-05-01 21:14 UTC, MamaikAn approved these changes

2020-05-01 21:14 UTC, FluffyF1sh approved these changes
Капец, Егор, а чего ты так тянул-то?

2020-05-02 03:46 UTC, TeplCold approved these changes

2020-05-02 03:47 UTC, merged