Поправил footer
ISRPO2019/ISRPO2019.github.io pull request #184
Opened 2020-05-03 18:48 UTC by Reptil0id

2020-05-03 19:12 UTC, TeplCold requested changes
Измени подвал так же на странице отдельного товара.
Добавь ссылку на issue.
![image](https://user-images.githubusercontent.com/38286808/80923229-6e645700-8d93-11ea-9f8a-408b0181669f.png)

2020-05-03 19:27 UTC, Reptil0id commented
Fixes #168

2020-05-03 21:05 UTC, FluffyF1sh requested changes
Сделай название пулла по типу "что сделано?", а не "что сделал?"

Также текст в кнопке на 576px выходит за её пределы
![image](https://user-images.githubusercontent.com/37347360/80925734-4e3c9400-8da3-11ea-9f61-aca3a73e2df5.png)

2020-05-03 21:43 UTC, FluffyF1sh requested changes
Сделать картинку под размер макета 320x70

Увеличить шрифт как в макете
![image](https://user-images.githubusercontent.com/37347360/80926390-0c621c80-8da8-11ea-9d5f-617c41f0f653.png)

Также шрифт на 767-991 должен быть 24px

Изменить размер кнопки под макет на 767-991

576px вёрстка не соответствует макету
Текущая: 
![image](https://user-images.githubusercontent.com/37347360/80926478-9f9b5200-8da8-11ea-80bd-f5e1289f88a2.png)
Макет: 
![image](https://user-images.githubusercontent.com/37347360/80926482-aa55e700-8da8-11ea-908e-b56ff944e658.png)


На 0-575px вёрстка ломается, сделай единую с 0 до 576

![image](https://user-images.githubusercontent.com/37347360/80926444-64991e80-8da8-11ea-993b-5b306efe26ad.png)

2020-05-04 11:01 UTC, MamaikAn commented on style/style.css
>      }
этот класс вообще убери из стилей, не твой старый косяк

2020-05-04 11:02 UTC, MamaikAn commented on style/style.css
> +@media screen and (min-width: 575px) and (max-width: 991px) {
min-width: 576

2020-05-04 11:03 UTC, MamaikAn commented on style/style.css
> +@media screen and (max-width: 765px) {
max-width: 767

2020-05-04 11:03 UTC, MamaikAn commented on style/style.css
> +@media screen and (min-width: 575px) and (max-width: 767px) {
min-width: 576

2020-05-04 11:04 UTC, MamaikAn commented on style/style.css
>  @media screen and (min-width: 575px) and (max-width: 641px) {
это видимо твой старый косяк, таких разрешений не существует, исправь

2020-05-04 11:14 UTC, MamaikAn requested changes
Разные шрифты:
![image](https://user-images.githubusercontent.com/38722519/80959227-094e4700-8e0f-11ea-9e2b-82f0ae0cb34a.png)

Макет планшета:
![image](https://user-images.githubusercontent.com/38722519/80959892-6e566c80-8e10-11ea-844f-39c4bcef7d36.png)

Планшет на сайте (в основном другой размер шрифта, границ у input + button в макете нет):
![image](https://user-images.githubusercontent.com/38722519/80959930-7ca48880-8e10-11ea-9857-9bca1b4323aa.png)

На разрешении 576-767 лучше сделай, чтобы кнопка "отправить" была под всеми input'ами, как на мобиле.

На мобиле (0-575) слишком большой шрифт во всем футере.

На мобиле поправить шрифты, увеличить отступы:
![image](https://user-images.githubusercontent.com/38722519/80960417-79f66300-8e11-11ea-9fec-6eabcf820aeb.png)

На мобиле (320px) текст внизу: 
![image](https://user-images.githubusercontent.com/38722519/80960457-96929b00-8e11-11ea-8a7c-b4746a010ae1.png)

2020-05-05 09:50 UTC, MamaikAn requested changes
Верстку не проверял.
Ты изменил подвал в index.html, измени и в product.
Далее в css: везде должны использоваться rem'ы, кроме мобилы, где для подвала специально указан font-size.

2020-05-05 19:08 UTC, TeplCold requested changes
Пусть 576-767 тоже мобила будет.
ПРОВЕРЬ ВНАЧАЛЕ ПОТОМ СДАЙ, УСТАЛИ УЖЕ!!!
![image](https://user-images.githubusercontent.com/38286808/81105624-4278db00-8f25-11ea-91b8-402e98ec74f3.png)
![image](https://user-images.githubusercontent.com/38286808/81105637-473d8f00-8f25-11ea-9ef6-fd413b2b7e40.png)

2020-05-06 14:25 UTC, Ge5akl commented
1) Footer отделен от оснвного блока:
![image](https://user-images.githubusercontent.com/38038269/81182089-6ccaa700-8fbe-11ea-9dd3-4d14f0551331.png)
Должно быть так как на макете: 
![image](https://user-images.githubusercontent.com/38038269/81182159-8370fe00-8fbe-11ea-997b-1d771eeb50ca.png)
2) Имеется отступ footer на мобильной верстке
![image](https://user-images.githubusercontent.com/38038269/81188600-912a8180-8fc6-11ea-8a62-53420b5fc579.png)

2020-05-22 17:50 UTC, MamaikAn commented on style/style.css
> +}
Это зачем?

2020-05-22 17:54 UTC, MamaikAn commented on style/style.css
> +}
Вроде и без этого стиля все хорошо, но может я что-то упустил?

2020-05-22 18:01 UTC, MamaikAn approved these changes
Красава, молодец, генералом будешь

2020-05-22 18:02 UTC, FluffyF1sh reviewed
Ой...

2020-05-22 18:03 UTC, FluffyF1sh approved these changes
Красава, молодец, генералом будешь

2020-05-22 18:17 UTC, TeplCold approved these changes

2020-05-22 18:22 UTC, merged