Сделан подвал (исправление)
ISRPO2019/ISRPO2019.github.io pull request #187
Opened 2020-05-07 18:52 UTC by Hasepchik

2020-05-13 13:44 UTC, TeplCold requested changes
Добавь ссылку на issue.
![image](https://user-images.githubusercontent.com/38286808/81820207-5df56e80-9541-11ea-83b6-530a43d5cfcb.png)

2020-05-17 17:04 UTC, FluffyF1sh requested changes
Добавь отступ для последнего блока, чтобы по центру было
![image](https://user-images.githubusercontent.com/37347360/82154899-0da04880-9882-11ea-9a57-43f3fb5b24a2.png)

2020-05-22 16:17 UTC, FluffyF1sh requested changes
Ничего не изменилось.

2020-05-22 17:28 UTC, FluffyF1sh approved these changes

2020-05-23 14:37 UTC, MamaikAn commented on style/style.css
>  }
Это здесь зачем?

2020-05-23 14:37 UTC, MamaikAn commented on style/style.css
> +    color: #FFFFFF;;
Убери лишнюю ;

2020-05-23 14:42 UTC, MamaikAn requested changes
Ничего не изменилось 
![image](https://user-images.githubusercontent.com/38722519/82733475-b9331800-9d1c-11ea-8128-f68b45c3cff5.png)

2020-05-23 15:25 UTC, MamaikAn requested changes
Смещение разделов должно быть только на разрешениях 992px и выше
![image](https://user-images.githubusercontent.com/38722519/82734269-a4598300-9d22-11ea-9fe7-ca983fa0c863.png)

Еще оставил комментарий выше про стили в css

2020-05-23 17:18 UTC, MamaikAn requested changes
Смещение на разрешениях 0-991 до сих пор осталось 
![image](https://user-images.githubusercontent.com/38722519/82736437-73814a00-9d32-11ea-941e-a47092adfb52.png)

2020-05-23 17:39 UTC, MamaikAn commented on style/style.css
>  }
Убрать повторение стилей для класса .ab, оставить только в одном месте.

2020-05-23 17:39 UTC, MamaikAn requested changes
Надо убрать отступ на 0-991, сейчас 0-767.
+ коммент выше

2020-05-23 18:52 UTC, MamaikAn requested changes
Этот участок кода перенеси в media max-width: 991
![image](https://user-images.githubusercontent.com/38722519/82738354-a0882980-9d3f-11ea-8f0f-8ecf883f4bd7.png)

2020-05-23 19:22 UTC, MamaikAn approved these changes

2020-05-23 19:49 UTC, FluffyF1sh approved these changes

2020-05-23 19:55 UTC, TeplCold approved these changes

2020-05-23 19:56 UTC, merged