Сделан конфигурационный файл
ISRPO2019/ISRPO2019.github.io pull request #44
Opened 2019-11-28 07:29 UTC by Mynalait

2019-11-28 07:33 UTC, FluffyF1sh requested changes
![image](https://user-images.githubusercontent.com/37347360/69785957-d2766400-11d2-11ea-8bbb-f5accd728e23.png)
Изменить форматирование, чтобы текст в тэгах был в отдельной строке.

2019-12-04 04:52 UTC, TeplCold requested changes
Внесите изменения указанные выше.

2019-12-05 05:47 UTC, Vladislav-Lyuminarskiy requested changes
Добавить конфигурационные файлы для статического анализа кода на HTML, CSS и JS.

2019-12-10 14:41 UTC, closed without merging

2019-12-11 05:53 UTC, TeplCold commented
#44