Был изменен local storage и добавлена сортировка
ISRPO2019/ISRPO2019.github.io pull request #88
Opened 2019-12-10 22:49 UTC by WartVader

В local storage было изменены оценки
Fixes #28

2019-12-10 23:05 UTC, TeplCold requested changes
![image](https://user-images.githubusercontent.com/38286808/70576535-9378e300-1bc2-11ea-92fd-334f3fccf766.png)
Нужно выводить бренд и имя, что уже было сделано #83.

2019-12-11 05:04 UTC, FluffyF1sh requested changes
00

2019-12-11 05:22 UTC, TeplCold approved these changes

2019-12-11 05:22 UTC, FluffyF1sh approved these changes
Принято.

2019-12-11 05:23 UTC, merged